name: Docker Image build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file static-website-boilerplate-master/Dockerfile --tag devops/static-website-boilerplate-master:latest
    
    - name: Run the Docker image
      run: docker run devops/static-website-boilerplate-master:latest
      
