name: Docker Image build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file static-website-boilerplate-master/Dockerfile --tags jankogaga/static-website-boilerplate-master:latest
    
    - name: Run Docker container
      uses: docker://jankogaga/static-website-boilerplate-master:latest
#       with:
#         args: your-command-to-run-in-container
        
    - name: Curl
      run: curl http://localhost:3000
      
